services:
  - type: web
    name: video-downloader
    env: node
    buildCommand: |
      apt-get install -y ffmpeg &&
      npm install &&
      mkdir -p bin &&
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp &&
      chmod +x bin/yt-dlp
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
